// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgX_LcrmadJbdLsUkxCW6b1BaqkNGbh70',
    appId: '1:482957862211:web:4abcf8173138fb12e1fbf6',
    messagingSenderId: '482957862211',
    projectId: 'vision-e0290',
    authDomain: 'vision-e0290.firebaseapp.com',
    storageBucket: 'vision-e0290.appspot.com',
    measurementId: 'G-S9SE77L5GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSbb455ib07PBefPXqxf91_CluTQl-XKM',
    appId: '1:482957862211:android:fcb0b41a9b053366e1fbf6',
    messagingSenderId: '482957862211',
    projectId: 'vision-e0290',
    storageBucket: 'vision-e0290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX3L98ArgZlsTzYz0L6Tm2Q3M6O_ewYVo',
    appId: '1:482957862211:ios:a98d3f8009f14849e1fbf6',
    messagingSenderId: '482957862211',
    projectId: 'vision-e0290',
    storageBucket: 'vision-e0290.appspot.com',
    iosBundleId: 'com.example.vision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX3L98ArgZlsTzYz0L6Tm2Q3M6O_ewYVo',
    appId: '1:482957862211:ios:a98d3f8009f14849e1fbf6',
    messagingSenderId: '482957862211',
    projectId: 'vision-e0290',
    storageBucket: 'vision-e0290.appspot.com',
    iosBundleId: 'com.example.vision',
  );
}
